version: "3.8"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - 2003:4000
    volumes:
      - ./bot:/app
    networks:
      - reyon_net
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 2002:4000
    volumes:
      - ./api:/app
    networks:
      - reyon_net

networks:
  reyon_net:
    driver: bridge